version: '3.8'

services:
  invinitive.api:
    container_name: invinitive-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./store/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invinitivePortfolios
      MYSQL_PASSWORD: 12345